### ISSUE TITLE
setting HTTP_PROXY

### ISSUE THREAD

**Issue by atomotic** [yujiosaka/headless-chrome-crawler#120]
**process.env.HTTP_PROXY** is not being passed to [puppeteer.launch()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables), tried with a running proxy and:

`env HTTP_PROXY=localhost:8000 node crawl.js`

**Comment by yujiosaka** [comment]
@atomotic 
Thanks for filing an issue!
I see puppeteer's document confusing. I read puppeteer's code and I found it uses `HTTP_PROXY` for downloading Chromium but not for running it.

Actually, it provides another way of using a proxy in this [example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/proxy.js).

headless-chrome-crawler passes `args` option to puppeteer when launching and connecting to a Chromium instance.
So it should work in this way:

```js
const HCCrawler = require('headless-chrome-crawler');

HCCrawler.launch({
  args: [ '--proxy-server=127.0.0.1:3128' ], // Pass proxy setting here
  onSuccess: (result => {
    console.log(`Requested ${result.options.url}.`);
  }),
})
  .then(crawler => {
    crawler.queue('https://example.com/');
    crawler.onIdle()
      .then(() => crawler.close());
  });
```

**Comment by atomotic** [comment]
good, thank you!
passing proxy in `args` works fine
