### ISSUE TITLE
A way to filter followed links or processed pages

### ISSUE THREAD

**Issue by vibl** [yujiosaka/headless-chrome-crawler#138]
I'm considering using this crawler. I couldn't find in the doc a way to filter:
- the links the crawler will follow (by url, by anchor text, by css/xpath, etc.);
- the pages the crawler will parse (by page title, content, header, etc.)
- the files the crawler will download (by mimetype, by size, etc.)

Is there a way that I missed? Or a workaround? Or is it a planned feature?

Three functions that return a boolean (to filter or not) might be enough.

**Comment by yujiosaka** [comment]
> the links the crawler will follow (by url, by anchor text, by css/xpath, etc.);

It can be done by `preRequest` option

> the pages the crawler will parse (by page title, content, header, etc.)

It can be done by `evaluatePage` option

> the files the crawler will download (by mimetype, by size, etc.)

It's not supported yet. Would you provide more use cases?

Crawling with `preRequest` and `evaluatePage` should go as follow:

```js
const HCCrawler = require('headless-chrome-crawler');

HCCrawler.launch({
  maxDepth: 3,
  preRequest: (options => {
    if (options.url.indexOf('https://www.iana.org/domains/') >= 0) return false; // Skip requesing by urls
    return true;
  }),
  evaluatePage: (() => {
    if (window.document.title.indexOf('RFC') >= 0) return null; // Stop evaluating page by DOM
    return { title:  window.document.title };
  }),
  onSuccess: (result => {
    if (!result.result) return; // Dont show result when evaluatePage's result is null
    console.log(`${result.result.title} ${result.options.url}.`);
  }),
})
  .then(crawler => {
    crawler.queue('https://example.com/');
    crawler.onIdle()
      .then(() => crawler.close());
  });
```

**Comment by vibl** [comment]
Wow, thanks!

The third feature (filtering by files mimetype or size) is less important. It might be needed in corner cases when we don't want to download big files (or certain types of files) but there is no way to detect them from the anchor name, attribute or location in the page, only from the HTTP headers. I admit this situation should be rare so we can forget it if nobody has had a need for it (I haven't yet, to be honest).

**Comment by BubuAnabelas** [comment]
You could access the HTTP headers by using the [pupeteer's API](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md) starting from the Page object which is exposed in the [`newpage` event](https://github.com/yujiosaka/headless-chrome-crawler#event-newpage). From there you should enabled the request interception which would give you the [request](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-request) and [response](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-response) events, specifically the [response.headers()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responseheaders) return object.

Tell me if you need more help.

**Comment by bobmaerten** [comment]
@BubuAnabelas and @yujiosaka correct me if I'm wrong but reading the source code, the Page object returned by `newpage` event should be treated as "readonly" as the whole callbacks thing would not trigger in the order we expect, to do such thing like `page.setRequestInterception(true)`. Crawling would already have started when the new page event would return the page object, am I right ?

**Comment by bobmaerten** [comment]
I personally wonder how I could manage setting Puppeteer request interception (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue) in in launch or queue configuration.

I would enjoy to have such a feature optimise crawling by telling chrome not to fetch images (or any kind of requests like js scripts) when I don't need to take a screenshot, or when I don't want to trigger external scripts.

**Comment by bobmaerten** [comment]
I autocorrect myself as I am wrong. I just tested @BubuAnabelas trick with success.

```javascript
 crawler.on("newpage", function(page) {
    page.setRequestInterception(true);
    page.on("request", function(interceptedRequest) {
      if (interceptedRequest.resourceType() == "image" ) {
        interceptedRequest.abort();
      } else {
        interceptedRequest.continue();
      }
    });
  });
```

**Comment by yujiosaka** [comment]
@vibl @BubuAnabelas @bobmaerten 

Thank you guys for questions and helps!
