### ISSUE TITLE
Crawl the initial URL twice

### ISSUE THREAD

**Issue by yvmarques** [yujiosaka/headless-chrome-crawler#144]
**What is the current behavior?**
Crawl twice the front page when the enqueued URL doesn't contain an end slash

**If the current behavior is a bug, please provide the steps to reproduce**
Configure a queue with a domain as https://example.com then the page has a link as `<a href="/">Home</a>`

**What is the expected behavior?**
It should only crawl once the front page

**What is the motivation / use case for changing the behavior?**
In case we export data from the initial page, we might have twice the data.

**Please tell us about your environment:**

- Version: 1.4.0
- Platform / OS version: Ubuntu 16.04 LTS
- Node.js version: 9.7.1

The current workaround is to ensure that we set a URL in the queue with the end slash.

**Comment by yujiosaka** [comment]
@yvmarques Thanks for reporting a bug!
