### ISSUE TITLE
Enable timeout as a valid queue option

### ISSUE THREAD

**Issue by bobmaerten** [yujiosaka/headless-chrome-crawler#149]
**What is the current behavior?**
`timeout` is not an overridable in the `crawler.queue()` options

**If the current behavior is a bug, please provide the steps to reproduce**

```javascript
const HCCrawler = require('headless-chrome-crawler');

HCCrawler.launch({
  evaluatePage: (() => ({
    title: $('title').text(),
  })),
  onSuccess: (result => {
    console.log(result);
  }),
})
  .then(crawler => {
    crawler.queue({ url: 'https://example.com/', timeout: 5});
    crawler.onIdle()
      .then(() => crawler.close());
  });
```

**What is the expected behavior?**

`timeout` should be a valid queue option 

**What is the motivation / use case for changing the behavior?**

I'd like to be able to set a per-request timeout like it's possible with puppeteer `goto` function.

**Please tell us about your environment:**

- Version: 1.4.0
- Platform / OS version: macOS 10.13.3
- Node.js version: v9.7.1

**Comment by bobmaerten** [comment]
`timeout` is a `LAUNCH_OPTIONS` key, and check for available queue keys is based on a concat of `CONNECT_OPTIONS`, `LAUNCH_OPTIONS` and `CONSTRUCTOR_OPTIONS`.

may be adding a `request_timeout` key would be more distinctive?

**Comment by yujiosaka** [comment]
@bobmaerten 
Thanks for tracking the code and suggesting a feature!

It turned out to be a bug. Actually, `timeout` option must be passed per-request as described in README as follows:

> The following options are passed to Puppeteer's page.goto()'s options'.
> timeout, waitUntil

However, it wasn't working simply because the option name is the same as the constructor option.

It was my fault, and I'll make a fix very quick!

**Comment by bobmaerten** [comment]
Nice! But take all the necessary time to find a good name for this option :)

**Comment by yujiosaka** [comment]
@bobmaerten 
Thanks for your kind advise!

I was about to follow your suggestion, renaming `timeout` to `requestTimeout`, but I realized that `timeout` does not consider only HTTP requests but also javascript events like `DOMContentLoaded` and `load` especially when you specify `waitUntil` option.

So probably `timeout` is the most general and proper name. I appreciate your suggest, though!
