### ISSUE TITLE
Adding a delay before evaluating page

### ISSUE THREAD

**Issue by bobmaerten** [yujiosaka/headless-chrome-crawler#150]
**What is the current behavior?**

Currently, `evaluatePage` is requested right after event specified in `waitUntil` option ("load" by default).

**What is the expected behavior?**

Be able to use the puppeteer `page.waitFor` method, to add a delay before evaluating the page or taking a screenshot

**What is the motivation / use case for changing the behavior?**

I'd like be able to take screenshot of a requested page, but after a short delay, to wait for any animation triggers by JS code to complete, or for instance, to wait for asynchronous JS code to be executed.

I tried to set the `waitUntil` option to `"networkidle0"` but it's not always enough.

**Comment by yujiosaka** [comment]
@bobmaerten 
Thanks for requesting a feature!

Your request sounds very compelling. I should work on that idea in the next version.
As for now, there is a workaround. You can return promise for `evaluatePage`, so you can actually writes code to wait for seconds, selectors and whatever you like to.

This is an example code:

```js
const HCCrawler = require('headless-chrome-crawler');

HCCrawler.launch({
  evaluatePage: (() => {
    const wait = () => new Promise(resolve => void setTimeout(resolve, 5000)); // wait for 5 sec
    return wait().then(() => $('body').text());
  }),
  onSuccess: (result => {
    console.log(`body: ${result.result}`);
  }),
})
  .then(crawler => {
    crawler.queue('http://localhost:8080/');
    crawler.onIdle()
      .then(() => crawler.close());
  });
```

**Comment by bobmaerten** [comment]
I'm not a very good JS dev and I tried very hard to do something like this for some time. Thanks, it's a good (and working for what I need) alternative!

**Comment by bobmaerten** [comment]
Changes added to master are much more convenient, though. Thanks again!
