### ISSUE TITLE
how to use html to text function in the export-csv sample

### ISSUE THREAD

**Issue by lx171717** [yujiosaka/headless-chrome-crawler#163]
**const htmlToText = require('html-to-text');**
const FILE = './tmp/result-sample.csv';

const exporter = new CSVExporter({
  file: FILE,
  fields: ['response.url', 'response.status', 'links.length','depth','result.content'],
});

HCCrawler.launch({
  maxDepth: 2,
  exporter,
  // Function to be evaluated in browsers
  evaluatePage: (() => ({
    **content: htmlToText.fromString($('html').text()),**
  })),
})

**Comment by Hoishin** [comment]
From my understanding, `evaluatePage` function is converted to string and run on browser with eval, so you cannot use npm packages directly.

**Comment by lx171717** [comment]
I want to use this crawler  for  crawling web and  download html files, do you have some code sample?

**Comment by Hoishin** [comment]
If I'd do that, I would just collect URLs with the crawler and separate downloading part using `request` or similar packages.

**Comment by yujiosaka** [comment]
> I want to use this crawler for crawling web and download html files

I believe @BubuAnabelas has answered the way to do this [here](https://github.com/BubuAnabelas).
Please reopen this issue if the problem is not solved.

**Comment by BubuAnabelas** [comment]
I answered in https://github.com/yujiosaka/headless-chrome-crawler/issues/164#issuecomment-374477580 (broken link above)
