### ISSUE TITLE
Is there a way to feed data in forms, such as text box, dropdowns, etc and submit the pages?

### ISSUE THREAD

**Issue by nnganesha** [yujiosaka/headless-chrome-crawler#165]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- Version:
- Platform / OS version:
- Node.js version:

**Comment by yujiosaka** [comment]
@nnganesha 

No, it's not possible. I'll appreciate if you can provide more use cases.
