### ISSUE TITLE
Suggestion: robots.txt denied event

### ISSUE THREAD

**Issue by panthony** [yujiosaka/headless-chrome-crawler#193]
**What is the current behavior?**

URLs denied by the robots.txt are silently swallowed.

**What is the expected behavior?**

When an URL is denied because of the robots.txt we should either have an event, a callback or something.

**What is the motivation / use case for changing the behavior?**

It could be useful to track all URLs that were discarded because of the robots.txt (and not because they were not found or whatever the reason)

**Comment by panthony** [comment]
I just saw that it was the purpose of "RequestSkipped".

Then maybe we just need to forward the reason so this event :)

**Comment by yujiosaka** [comment]
Good point!
