### ISSUE TITLE
Question: skipDuplicates and redirections

### ISSUE THREAD

**Issue by panthony** [yujiosaka/headless-chrome-crawler#197]
**What is the current behavior?**

For the following structure:
- 'https://domain.com/path'
- 'http://domain.com/path' redirecting to 'https://domain.com/path'

We will crawl and export 'https://domain.com/path' twice even with `skipDuplicates:true`.

**What is the expected behavior?**

I know that for my use-case I should not have crawl the url twice.

But I was wondering if you were aware of this behavior and what was your thought on this?

Do you think it's expected to crawl it again or it shouldn't have?

**Comment by panthony** [comment]
@yujiosaka The issue with redirections and a distributed crawler is that you cannot guarantee you won't crawl the URL twice.

You would have to stop at the redirection and push the `location` back to the queue (same as it's done with links).

I did a quick & dirty workaround that seems to work:

https://github.com/cogniteev/headless-chrome-crawler/compare/cogniteev:51f0a07b4940a00265065877d739a8a2a8c19af2...cogniteev:155625a09da025c3c2a3ca1d3b65056fbf59886f

The idea is to emit a redirection like a resolved url.

(I'm currently trying to figure out if a crawler based on puppeteer could be a viable solution for my use cases.)

**Comment by yujiosaka** [comment]
closing for now in the believe that most of the need is satisfied by `redirectChain` and `skipRequestedRedirect` features implemented [here](https://github.com/yujiosaka/headless-chrome-crawler/pull/223).

Feel free to reopen this issue if needed.
