### ISSUE TITLE
Ease tests running

### ISSUE THREAD

**Issue by panthony** [yujiosaka/headless-chrome-crawler#203]
**What is the current behavior?**

`npm test` fails out of the box.

**What is the expected behavior?**

This command should works.

Or at least the README should provide easy step to make them run.

But would be better for 'npm test' to just work.

Maybe https://www.npmjs.com/package/redis-mock or similar?

**What is the motivation / use case for changing the behavior?**

Hard to motivate people to contribue and write tests when the tests won't run to begin with :)

**Comment by yujiosaka** [comment]
@panthony 
Never thought of that! Thanks for a good issue!
