### ISSUE TITLE
Question: Extending/Customizing the behavior of crawler

### ISSUE THREAD

**Issue by panthony** [yujiosaka/headless-chrome-crawler#204]
**What is the current behavior?**

Current crawler takes some arbitrary decision on what to keep with no way for the user to do differently.

**What is the expected behavior?**

It should be possible to customize/extend the behavior to some extent.

For exemple today, only the following fields are returned from the response:

```
  'ok',
  'url',
  'status',
  'headers',
```

Maybe I'd like something more? Maybe what I want is the result of a method returning a promise?

I see 2 ways of doing this:

- Either expose more options (but that could be too many options)

- Expose the 'Crawler' class, makes some methods public (ex: serializeResponse, serializeRequest, ...) and make it possible to pass it to the HCCrawler. This way one could extend the crawler to override the behavior of some of the methods.

I'd prefer the later since, with a nice chosen public API, it would be possible to customize easily the behavior of the crawler without exposing dozens and dozens of options.

**What is the motivation / use case for changing the behavior?**

I need the redirectChain of the request, the HTTP headers of the request, the returns of the text() method from the response...

This is difficult to satisfy all needs with a generic implementation so it should be extendable.

**Comment by yujiosaka** [comment]
@panthony 
Thanks for a good issue as always!

I think both suggestions are brilliant. This time let me solve this issue by supporting `redirectChain` because I need it, too.
Let's think about supporting `serializeResponse` when other options are requested!

**Comment by panthony** [comment]
@yujiosaka Actually for me redirectChain is not enough, because you cannot ensure that you won't fetch the same URL twice.

In my case I need to prevent the browser from following the redirection automatically (like here: https://github.com/yujiosaka/headless-chrome-crawler/issues/197#issuecomment-378584367) and return a response with a 3xx status code instead.

But the idea behind the extended crawler is to allow people to access the underlying puppeteer object without having to add more code to this repository.

This way you can benefit from puppeteer new features directly.

For exemple, I need to access the underlying crawler because I want to intercept some of the browser requests.

I don't care for images, fonts, stylesheets. I want to intercept any analytics ajax calls etc.

**Comment by panthony** [comment]
Yeah for now I'm really exploring what can be done or not be done.

Maybe I won't be able to use this project directly because of my very specific use case or maybe I won't be able to use puppeteer at all because it isn't reliable enough for now.

**Comment by yujiosaka** [comment]
closing for now in the believe that most of the need is satisfied by `redirectChain` and `skipRequestedRedirect` features implemented [here](https://github.com/yujiosaka/headless-chrome-crawler/pull/223).

Feel free to reopen this issue if needed.
