### ISSUE TITLE
NPM doesnt install "headless-chrome-crawler"

### ISSUE THREAD

**Issue by AlonsoK28** [yujiosaka/headless-chrome-crawler#226]
**What is the current behavior?**
NPM doesnt install "headless-chrome-crawler", show the following error: "npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "headless-chrome-crawler" under a package
npm ERR! also called "headless-chrome-crawler". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AlonsoK\AppData\Roaming\npm-cache\_logs\2018-04-25T23_30_57_436Z-debug.log"

**If the current behavior is a bug, please provide the steps to reproduce**
npm i headless-chrome-crawler

**What is the expected behavior?**
NPM "install headless-chrome-crawler" package

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**

- Version: NPV version 5.6.0
- Platform / OS version:
- Node.js version: v8.9.4

**Comment by yujiosaka** [comment]
@AlonsoK28

The error message already told you the exact reason.

> Refusing to install package with name "headless-chrome-crawler" under a package
npm ERR! also called "headless-chrome-crawler". 

Modify the directory name to something different from headless-chrome-crawler.
