### ISSUE TITLE
Screenshot with currency other than 1 not working

### ISSUE THREAD

**Issue by GrumpyMeow** [yujiosaka/headless-chrome-crawler#248]
**What is the current behavior?**
I wrote a crawler which crawls websites. When i specify that this crawler uses multiple concurrent browsertabs, not all screenshots are made.
If i modify the concurrency to "1", all screenshots are made correctly.

**If the current behavior is a bug, please provide the steps to reproduce**
preRequest: (options => {
			console.log('Requesting:' + options.url);
			var shaUrl = new shajs.sha256;
			shaUrl.update(options.url);
            var shaUrlHex = shaUrl.digest('hex');
			if (screenshot) { options.screenshot =  { path: repositoryfolder + snapfolder + '/' + shaUrlHex + ".png" , fullPage: true};}
			return true;
		})

**What is the expected behavior?**
I would expect that all screenshots would be written to disk.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- Version:
- Platform / OS version: Windows 10
- Node.js version:  v8.7.0

**Comment by yujiosaka** [comment]
@GrumpyMeow Do you have any update?

**Comment by yujiosaka** [comment]
Closing this issue because no information is provided for a month.
Please feel free to reopen it if you have further questions.
