### ISSUE TITLE
How to get all cookies?

### ISSUE THREAD

**Issue by pandacoder** [yujiosaka/headless-chrome-crawler#254]
Hi yujiosaka,

**I'm trying to retrieve all the cookies on a page (1st and third party cookies).**

The default `result.cookies` only contains 1st party cookies:

```
onSuccess: (result => {
    console.log(result.cookies);
}),
```

There is a way with [Puppeteer to get all cookies, including third party](https://stackoverflow.com/questions/50252943/puppeteer-get-3rd-party-cookies)  with the `await page._client.send('Network.getAllCookies'));` method. 

So I'm trying to use that with the crawler, however the `onSuccess` method only returns `result` which doesn't contain a reference to Puppeteer's `page` object.

**Do you know where I can call the `async page._client.send('Network.getAllCookies'));` method so I can retrieve all cookies (1st/third) on every crawled page?**

Many thanks

**Comment by yujiosaka** [comment]
@pandacoder 

That's a very interesting use case and I love it!

Currently, there is no way retrieving all cookies including third party ones.
The crawler exposes puppeteer's raw `page` object by `newpage` event, but it doesn't help you achieve the goal.

Sure, I can implement a feature to call `'Network.getAllCookies'` for the specific case. It must be useful.
At the same time, it's about time for me to start thinking about providing another general solution to expose `page` object.

For me your fundamental needs sound similar to https://github.com/yujiosaka/headless-chrome-crawler/pull/233.
What do you think?

**Comment by BubuAnabelas** [comment]
Reading these it came to me the thought that maybe it would be useful to expose the [CDPSession](https://github.com/GoogleChrome/puppeteer/blob/v1.4.0/docs/api.md#class-cdpsession) (and perhaps building some utils to get/set the cookies and things like that) without accessing through the `target` object through the `page` object. That way you can access a lot of the underlying features of Puppeteer and Chrome.

**Comment by BubuAnabelas** [comment]
@yujiosaka 

You're right, it should be done with specific functions.
It can be limited to certain events like `requeststarted` and `requestfinished`.
That way you can have some sort of custom scraper for each page or request (as in #233)

**Comment by pandacoder** [comment]
@yujiosaka 

I'm not a pro coder so please take my feedback accordingly. My general design approach would be to:

- **Do one thing do it well**: focus `headless-chrome-crawler` development on crawler features (links discovery, queuing, concurrency, caching etc..) so it becomes the best library for doing that.
- **Everything else? Hand over**: expose the underlying components (`browser`, `page`) so we can use them freely.

Too often I see helper libraries (built on top of main libraries) which abstract the source libraries too much, to a point that most features from the source libraries aren't available, so you end up ditching the helper library and write your own code (which defeats the point of the helper library which is to save you from re-inventing the wheel).

As for where/when expose the underlying components (`browser`,`page`), this is my naive thought: why not simply replicate all Page events?

```
class: Page
event: 'close'
event: 'console'
event: 'dialog'
event: 'domcontentloaded'
event: 'error'
event: 'frameattached'
event: 'framedetached'
event: 'framenavigated'
event: 'load'
event: 'metrics'
event: 'pageerror'
event: 'request'
event: 'requestfailed'
event: 'requestfinished'
event: 'response'
```

**Comment by yujiosaka** [comment]
Seems https://github.com/yujiosaka/headless-chrome-crawler/issues/256 is related in terms of the necessity of adding general purpose function.

**Comment by Zeikko** [comment]
With `headless-chrome-crawler`version 1.8.0 you can use this customCrawl function to get all cookies:
```
async function customCrawl(page, crawl) {
  const result = await crawl();
  const cookies = await page._client.send('Network.getAllCookies');
  result.cookies = cookies.cookies;
  return result;
}
```
