### ISSUE TITLE
Any way to get console warnings and errors?

### ISSUE THREAD

**Issue by langillerr** [yujiosaka/headless-chrome-crawler#256]
I'm just getting started with the crawler, and so far it's fantastic.  The one feature I'm looking for is to be able to log javascript warnings and errors to the json-line logger.

I see that in the crawler it's supposed to log errors, but I'm not actually seeing those anywhere (console or log).  I'm also not seeing anything about warnings or how to capture and log them.

Motivation: Just upgraded jQuery across our site that has a few hundred thousand pages, and I'm trying to find all of the jQuery Migrate warnings.

**Comment by langillerr** [comment]
Of course I find more info right after I post this. After a bit of digging I see that you can trigger it with `env DEBUG hccrawler:console` and print them out to the console, but I still am looking for a way to include it in the exporter.

I see that in puppeteer you can do so with the `page.on('console, ...`  approach, but that part is abstracted away for the hccrawler in an internal function that triggers before the page request.  I don't see a clean way of adding it without hacking up the cralwer code.

Ideas?  If not, maybe a fork and PR...

**Comment by yujiosaka** [comment]
@langillerr 
You can try by [this feature](https://github.com/yujiosaka/headless-chrome-crawler/pull/275)
Please let me know if you face a problem!

**Comment by langillerr** [comment]
@yujiosaka 

Thank you for the feature update!  I'm starting to dive in and while it looks promising, so far I'm not having much luck.

With your example above (as-is) or with it integrated into my current crawler script, I'm only seeing it crawl one page and then it stops.  I tried looking in crawler.js for the original implementation to see if something was missing or configured incorrectly, but nothing stood out as the issue. 

Is there an example of how to tell the crawler to proceed to the next link?

Here is my code:

`const HCCrawler = require('headless-chrome-crawler');
const RedisCache = require('headless-chrome-crawler/cache/redis');

const cache = new RedisCache({ host: '127.0.0.1', port: 6379 });

const JSONLineExporter = require('headless-chrome-crawler/exporter/json-line');

const FILE = './result.json';

const exporter = new JSONLineExporter({
  file: FILE,
  fields: ['response.url', 'response.status', 'messages'],
});

function launch(persistCache) {
  return HCCrawler.launch({
    allowedDomains: [ REDACTED ],
    deniedDomains: [ REDACTED ],
    maxRequest: 1000,
    maxConcurrency: 3,
    exporter: exporter,
    maxDepth: 500,
    retryCount: 3,
    viewport: {width:1920, height:1080},
    onSuccess: result => {
      console.log(`Got ${result.response.status} for ${result.options.url}.`);
    },
    customCrawl: async (page, crawl) => {
      // You can access the page object before requests
      await page.setRequestInterception(true);
      page.on('request', request => {
        if (request.url().endsWith('/')) {
          request.continue();
        } else {
          request.abort();
        }
      });
      page.on('pageerror', pageerr=> {
        console.log("Page Error: " + pageerr.message);
      });
      // The result contains options, links, cookies and etc.
      const result = await crawl();
      // You can access the page object after requests
      result.content = await page.content();
      // You need to extend and return the crawled result
      return result;
    },
    cache,
    persistCache, // Cache won't be cleared when closing the crawler if set true
  });
}

(async () => {
  const crawler1 = await launch(true); // Launch the crawler with persisting cache
  await crawler1.clearCache();
  await crawler1.queue('REDACTED');
  await crawler1.onIdle();
  await crawler1.close(); // Close the crawler but cache won't be cleared
})();
`
