### ISSUE TITLE
Mixed content causes a queued item to remain pending indefinitely

### ISSUE THREAD

**Issue by cameronbraid** [yujiosaka/headless-chrome-crawler#260]
**What is the current behavior?**

When a HTTPS url is crawled that contains mixed content (e.g. http iframe tag) the crawler never calls onSuccess callback or emits requestfinished or onError callback or emits requestfailed and pendingQueueSize never returns to 0

**If the current behavior is a bug, please provide the steps to reproduce**

Crawl a HTTPS page that includes a http image or iframe tag

**What is the expected behavior?**

Good question... I would expect that the onError callback and requestfailed event is emitted

**What is the motivation / use case for changing the behavior?**

The crawl never ends and there is no notiifcation as to why

**Please tell us about your environment:**

- Version: 1.7.0
- Platform / OS version: linux
- Node.js version: v8.11.2

**Comment by yujiosaka** [comment]
@cameronbraid 
Thanks for reporting an issue! I reported upstream [here](https://github.com/GoogleChrome/puppeteer/issues/2709).

**Comment by maartenvantjonger** [comment]
I had the same problem on a page like https://bennish.net/mixed-content.html
This can be resolved by changing _collectLinks in crawler.js to:

`
  /**
   * @return {!Promise<!Array<!string>>}
   * @private
   */
  async _collectLinks() {
    const links = await this._page.evaluate(() => {
    const links = await this._page.$$eval('a[href]', as => as.map(a => a.href));
    return uniq(links);
  }
`

**Comment by LeMoussel** [comment]
Find another bug with `page.exposeFunction`. 
See [Puppeteer wrong result with evaluate() & exposeFunction()](https://stackoverflow.com/questions/56794948/puppeteer-wrong-result-with-evaluate-exposefunction/56795211).

**Comment by kulikalov** [comment]
should be resolved with puppeteer update to v1.20.0
