### ISSUE TITLE
Priority suggestion

### ISSUE THREAD

**Issue by csakis** [yujiosaka/headless-chrome-crawler#284]
**What is the current behavior?**
Higher priority number executes before lower priority number

**If the current behavior is a bug, please provide the steps to reproduce**
Not a bug, just a suggestion

**What is the expected behavior?**
I believe, this is confusing. No 1 priority should be executed before No 2. I think it's less ambiguous 

**What is the motivation / use case for changing the behavior?**
Trying to help

**Please tell us about your environment:**

- Version:
- Platform / OS version:
- Node.js version:

**Comment by kulikalov** [comment]
this is a subjective preference and would require changes in backward-incompatible or ugly "alternative config" manner. So, if no one has a strong opinion toward this change, I'm closing this.
