### ISSUE TITLE
deniedDomains

### ISSUE THREAD

**Issue by csakis** [yujiosaka/headless-chrome-crawler#285]
**What is the current behavior?**
I am not able to deny domains

**If the current behavior is a bug, please provide the steps to reproduce**
return HCCrawler.launch({
        maxDepth: 2,
        headless: true,
        onSuccess: result => {
            console.log(`Requested ${result.options.url}.`);
        },
        deniedDomains: 'google', 
        cache,
        persistCache, // Cache won't be cleared when closing the crawler if set true
    });

**What is the expected behavior?**
google links should not show up in crawl.

**What is the motivation / use case for changing the behavior?**

Help make deniedDomain option work

**Please tell us about your environment:**

- Version: 1.8.0
- Platform / OS version: Windows 10
- Node.js version:10.4.0

**Comment by BubuAnabelas** [comment]
`deniedDomains` expects an Array with strings and regular expressions to deny.
It should be something like: `deniedDomains: ['google', 'etc']`

**Comment by csakis** [comment]
I tried with a simple string and an array of strings, but in both cases, I still scraped the deniedDomains

**Comment by BubuAnabelas** [comment]
Reading the code https://github.com/yujiosaka/headless-chrome-crawler/blob/033d7689a14d4654e99c7fa0719010240256828f/lib/helper.js#L125-L135
In line 132 it checks if the passed domain is a RegExp and if it is, it tests it against the hostname and checks if it should continue with the request or abort it.
If it isn't a RegExp, in line 133 it make a strict equality check against the hostname and decides if continues with the request or abort it.

So if you want to deny any domain that has 'google' in its hostname you should pass `deniedDomains: [/google/]` as the argument.

**Comment by csakis** [comment]
I tried that, too. It didn't make any difference:

**Comment by kulikalov** [comment]
@csakis do you still need help with that? I know, it might be a bit late 😄
Closing for now.
