### ISSUE TITLE
result.links get failed

### ISSUE THREAD

**Issue by u609** [yujiosaka/headless-chrome-crawler#290]
My code:

const HCCrawler = require('headless-chrome-crawler');

(async () => {
  const crawler = await HCCrawler.launch({
    evaluatePage: () => ({
      title: $('title').text(),
    }),
    onSuccess: result => {
     console.log(`Got ${result.links.length} links.`);
    },
  });
  await crawler.queue('http://jsgyq.jinshan.gov.cn/html/'); // Queue a request
  await crawler.onIdle();
  await crawler.close();
})();

the result is :Got 2 links.

but ,actually there are lots of links in 'http://jsgyq.jinshan.gov.cn/html/'

who can tell me the reason , thanks.

**Comment by u609** [comment]
i'm here still waiting…thanks

**Comment by ShironM2302** [comment]
You could change the maxDepth option, I think the default is two, so will only go two layers deep
