### ISSUE TITLE
Accessing the Puppeteer methods.

### ISSUE THREAD

**Issue by ydennisy** [yujiosaka/headless-chrome-crawler#303]
It would be great to be able to access some of the lower level puppeteer methods, especially page level manipulation and interactions such as:
`page.setRequestInterception(true)`

Is there a known workaround for this today?

**Comment by TriVectorX** [comment]
As far as I know, you could achieve it with custom crawl function call:

`return async(page, crawl) => {
            await page.setRequestInterception(interceptedRequestValue);
            page.on('request', interceptedRequest => {
                if (interceptedRequest.resourceType() == "image" || interceptedRequest.resourceType() == "css" || interceptedRequest.resourceType() == "media") {
                    interceptedRequest.abort();
                } else {
                    interceptedRequest.continue();
                }

            });
            const result = await crawl();
            result.content = await page.content();

            return result;
        }`

**Comment by kulikalov** [comment]
closing this issue, assuming it's resolved.
@ydennisy let me know if you still need help resolving this?
