### ISSUE TITLE
crawl multipages in parallel

### ISSUE THREAD

**Issue by Devhercule** [yujiosaka/headless-chrome-crawler#304]
**What is the current behavior?**

only one page is crawled at once. There is no multipage crawl in parallel.

**What is the expected behavior?**

Possibility to open n pages in parallel, like in puppeteer  by creating multiple pages via `browser.newPage` method, we can have many pages opened at the same time in puppeteer.

Is that possible with HCC?

**What is the motivation ?**

performance, rapidity

**Please tell us about your environment:**

- Version: lastest
- Platform / OS version: Centos 1.6
- Node.js version: v1.8.4

**Comment by easingthemes** [comment]
This already exists.
First initial url is crawled to retrieve all the links.
After that, all next pages are handled in parallel.

**Comment by popstas** [comment]
Use `maxConcurrency` option.
