### ISSUE TITLE
Passing arguments to evaluatePage()

### ISSUE THREAD

**Issue by arthurakay** [yujiosaka/headless-chrome-crawler#306]
**What is the current behavior?**

```
  async _scrape() {
    if (!this._options.evaluatePage) return null;
    await this._addJQuery();
    return this._page.evaluate(this._options.evaluatePage);
  }
```

See the [Puppeteer docs](https://github.com/GoogleChrome/puppeteer/blob/v1.7.0/docs/api.md#pageevaluatepagefunction-args) -- `evaluatePage()` can be passed arguments.

`headless-chrome-crawler` does not allow me to pass arguments to the function.

**What is the motivation / use case for changing the behavior?**

It would be nice to have access to variables from outside of the page context; e.g., if I needed code to `eval` in the page context.

Solution could be something like the following:

```
  async _scrape() {
    if (!this._options.evaluatePage) return null;
    await this._addJQuery();
    return this._page.evaluate(this._options.evaluatePage, this._options.evaluatePageArguments);
  }
```

I can issue a pull request for this (including some updates to the documentation), but I wanted to ask if this would even be considered/accepted first.

**Comment by gpakosz** [comment]
Would this permit calling Node code from within `evaluatePage()` ?

**Comment by arthurakay** [comment]
Having done a bit of digging, I have come up with the solution I'm really asking for:

```
  /**
   * @return {!Promise}
   * @private
   */
  async _scrape() {
    if (!this._options.evaluatePage) return null;
    await this._addJQuery();
    if (this._options.exposeFunction && this._options.exposedFunctionName) {
      await this._page.exposeFunction(this._options.exposedFunctionName, this._options.exposeFunction);
    }

    return this._page.evaluate(this._options.evaluatePage);
  }
```

Effectively I want `exposeFunction()` from Puppeteer so that I can pull some code I have in the NodeJS context into the `Page` context, like in the following example:

```
    return HCCrawler.launch({
        // see exposeFunction() below...
        evaluatePage: async () => {
            const extractors = await window.__getExtractors();
            // do some stuff; for example, eval() some utilities (defined in NodeJS) within the Page context

            return {
              // ...
            };
        },
        exposedFunctionName: '__getExtractors',
        exposeFunction: () => getExtractors(),
        onSuccess: result => {
            console.log(JSON.stringify(result.result));
        }
    });
```

This all works swimmingly and I'l issue a PR.

**Comment by tomothumb** [comment]
I send PR for this issue.
My commit is changes for passing args to evaluatePage simply.

Please check my changes.
https://github.com/yujiosaka/headless-chrome-crawler/pull/324

Then, example is here
```
HCCrawler.launch({
    evaluatePage: ((args) => ({
        title: $('title').text()
        foo: args.arg1,
        bar: args.arg2
    })),
    evaluatePageArgs: {
        arg1 : 'foo',
        arg2 : 'bar',
    },
…
})
```

`exposeFunction` PR of @arthurakay is good feature, but it is a little different from the this issue subject. I think it should add another issue thread for exposeFunction.

**Comment by arthurakay** [comment]
@BubuAnabelas BINGO thanks! I hadn't even seen that `customCrawl()` before.

In case anyone stumbles across this, here's my solution:

```
    /**
     * Function that runs in the context of the browser window
     */
    const evaluatePage = async () => {
        const extractors = await window.__exposedFunction();
        // ...stuff...
        return {
            error: error,
            data: returnData
        };
    };

    //...

    return HCCrawler.launch({
        customCrawl: async (page, crawl) => {
            const result = await crawl();

            await page.exposeFunction('__exposedFunction', () => {
                // stuff I want exposed!
                return {};
            });
            result.result = await page.evaluate(evaluatePage);

            return result;
        },

        onSuccess: result => {
            const url = result.options.url;
            const resultData = result.result;
            // ...stuff...
        }
    });
```
