### ISSUE TITLE
PseudoUrl

### ISSUE THREAD

**Issue by joshhopkins** [yujiosaka/headless-chrome-crawler#309]
**What is the expected behavior?**

Be great to be able to define pseudo urls. Expected behaviour detailed [here](https://www.apify.com/docs/sdk/apify-runtime-js/latest#PseudoUrl).

**What is the motivation / use case for changing the behavior?**

Provides a simple way of defining URL's to queue using regexp.

**Please tell us about your environment:**

- Version: 1.8
- Platform / OS version: MacOS
- Node.js version: 8.11.3

**Comment by kulikalov** [comment]
Hey @joshhopkins!
Pls correct me if I'm wrong, but I assume that this is solvable with `allowedDomains` config?
Let me know, if it's not, I'll reopen this issue.
