### ISSUE TITLE
Ignoring device and userAgent

### ISSUE THREAD

**Issue by joshhopkins** [yujiosaka/headless-chrome-crawler#310]
**What is the current behavior?**

When calling `crawler.queue()` with defined `url`, `device` and `userAgent` options are ignored.

**If the current behavior is a bug, please provide the steps to reproduce**

```
const HCCrawler = require('headless-chrome-crawler');

(async () => {
    try {
         const crawler = await HCCrawler.launch({
            headless: true,
            evaluatePage: (() => ({
                userAgent: window.navigator.userAgent,
            })),
            onSuccess: (crawler => {
                console.log(crawler.result)
            }),
          })

          await crawler.queue('http://www.whatsmyua.info/', {
            device: 'Nexus 7'
          })

          await crawler.onIdle()
          await crawler.close()

    } catch (error) {
        console.log(error)
    }
})();

```

Resolves with the default user-agent, not emulated.

**What is the expected behavior?**

The same behaviour as when defining `url` with `crawler.launch()`, as per [this example](https://github.com/yujiosaka/headless-chrome-crawler/blob/cd541902cfee529231f9f77f6088b399fa3f3a30/examples/emulate-device.js).

**Please tell us about your environment:**

- Version: 1.8.0
- Platform / OS version: Mac OS X 10_13_5 
- Node.js version: 8.11.3

**Comment by BubuAnabelas** [comment]
I think the problem in your code is that [`crawler.queue` expects either a string (url) or an object (options)](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/docs/API.md#crawlerqueueoptions).
So you should do the following for it to work as expected:
```javascript
await crawler.queue({
    url: 'http://www.whatsmyua.info/',
    device: 'Nexus 7'
})
```

Hope it fixes your problem.

**Comment by BubuAnabelas** [comment]
If it worked please close the issue, either way comment what's the current status of your problem
