### ISSUE TITLE
allowedDomains and deniedDomains  parameters are not work

### ISSUE THREAD

**Issue by liufuhu** [yujiosaka/headless-chrome-crawler#318]
**What is the current behavior?**
I set like this:
```
crawler.queue({
    url: 'https://a.example.com',
    obeyRobotsTxt: false,
    maxDepth: 2,
    depthPriority: true,
    allowedDomains: [/example\.com$/],
  });
```
but the argument options of function ```_checkAllowedDomains``` in the lib/hccrawler.js, the options does not include  the ```allowedDomains``` setting.

**If the current behavior is a bug, please provide the steps to reproduce**
It is a bug, please check.  The package version is 1.8.0

**Comment by BubuAnabelas** [comment]
The code looks good so I think it should work like that.

The `_checkAllowedDomains` function passes the array to the [`checkDomainMatch` function](https://github.com/yujiosaka/headless-chrome-crawler/blob/cd541902cfee529231f9f77f6088b399fa3f3a30/lib/helper.js#L130-L135) that makes a regular JS regex test against the requested url.

If you found out what's wrong please post it here.

**Comment by kulikalov** [comment]
@liufuhu are you still experiencing this issue? I wasn't able to reproduce the issue based on your example.
Let me know if so, I'll reopen it.
