### ISSUE TITLE
Suggestion: crawl results can be saved as sitemap.xml

### ISSUE THREAD

**Issue by kamanwu-oicr** [yujiosaka/headless-chrome-crawler#319]
Use a crawler to generator the sitemap.xml dynamically.  Is this a new feature or exist feature?

**Comment by joshhopkins** [comment]
You could try https://www.npmjs.com/package/sitemap-generator

**Comment by markgoho** [comment]
sitemap-generator is for static html

**Comment by joshhopkins** [comment]
Yes, but sitemap-generator can generate sitemaps dynamically. Now I see the OP is probably interested in generating dynamic sitemaps for dynamic sites.

**Comment by kulikalov** [comment]
@kamanwu-oicr did you figure it out?
