### ISSUE TITLE
Crawling not working when maxConcurrency is not 1

### ISSUE THREAD

**Issue by simlevesque** [yujiosaka/headless-chrome-crawler#325]
I think it's the same bug as : https://github.com/yujiosaka/headless-chrome-crawler/issues/248

**What is the current behavior?**
My crawler fetches a page and the evaluation function returns a function which fetches another page.
If I set the concurrency to zero, the data is properly fetched. I get the data from the fetch and it is returned to me. If the concurrency is bigger than 1, the data is not returned.

**What is the expected behavior?**
No matter the concurrency, the evaluated function should return the same content.

**Please tell us about your environment:**

- Version: 1.8
- Platform / OS version: Ubuntu 17.10
- Node.js version: 10.11

**Comment by BubuAnabelas** [comment]
It would be useful if you share the code used to replicate the bug.
@yujiosaka should take a look at this.

**Comment by kulikalov** [comment]
closing, since no further info followed. Concurrency seems to work fine.
