### ISSUE TITLE
crawling website with hashes in url

### ISSUE THREAD

**Issue by jlvdh** [yujiosaka/headless-chrome-crawler#332]
**What is the current behavior?**

Crawling a website that uses # (hashes) for url navigation does not crawl the pages that use #

The urls using # are not followed.

**If the current behavior is a bug, please provide the steps to reproduce**

Try crawling a website like mykita.com/en/

**What is the motivation / use case for changing the behavior?**

Though hashes are not ment to change a page, it is sometimes used by webdevelopers. It would be great to provide an option to crawl urls containing hashes so headless chrome crawler could be used for these pages.

Some research shows it might be an issue with puppeteer:

https://github.com/GoogleChrome/puppeteer/issues/257

And there seems to be a workaround:

https://github.com/GoogleChromeLabs/puppeteer-examples/blob/master/hash_navigation.js

**Comment by BubuAnabelas** [comment]
Maybe that workaround can be used inside the customCrawl function since it exposes puppeteer's Page.
Please tell us if that worked and how did you do it!

**Comment by kulikalov** [comment]
Should be resolved with puppeteer version update
