### ISSUE TITLE
Load Page Images

### ISSUE THREAD

**Issue by amerlin** [yujiosaka/headless-chrome-crawler#335]
Hi, 
I need get all page's images src attribute.
Now, I do it in evaluatePage function, but I don't  know if is the correct way. 

This is my evalutepage: 

 evaluatePage: (() => {
            var images = [];
            $('img').each(function (i, value) {
                images.push($(this).attr('src'));
            });
            return { images: images };
        })

then in onSuccess method can find images array with all src. 
Sometimes I received this error: 
Connection closed. Most likely the page has been closed.

I think the problem is the each function: the connection is closed, but in reality it has not finished processing.

Is this the correct way to get all page images? 
Thanks

**Comment by kulikalov** [comment]
Hey @amerlin 
```javascript
{
  evaluatePage: (() => document.querySelectorAll('img').forEach(img => console.log(img.src))
}
```

Sorry for a really late reply 😄 Hope it helps, pls don't hesitate to let me know if it didn't.
