### ISSUE TITLE
Dynamically named screenshots

### ISSUE THREAD

**Issue by Zsoltbenyey** [yujiosaka/headless-chrome-crawler#337]
**What is the current behavior?**
Hello, 
I am trying and are unable to crawl trough a page and create a screenshot for all the pages and name the screenshots after the current url. 

This is probably a really stupid question but it is my first time working with js async functions and i still don't understand how they work. 
 
- Version:
- Platform / OS version:
- Node.js version:

**Comment by matheuschimelli** [comment]
Please, provide your code here, so i can try help you

**Comment by igna92ts** [comment]
Im having this same issue
code is like this
```
const startCrawler = async () => {
  const crawler = await HCCrawler.launch({
    /* eslint-disable no-undef */
    browserCache: false,
    evaluatePage: () => ({
      title: $('title').text(),
      body: $('body').html()
    }),
    /* eslint-enable no-undef */
    onSuccess: result => {
      console.log(result);
    },
    onError: err => {
      console.log(err);
    }
  });
  await crawler.queue(
    urlList.map(c => ({
      url: c,
      userAgent: pickRandomElement(userAgents),
      screenshot: {
        path: `./sreenshots/${Buffer.from(c).toString('base64')}.png`
      }
    }))
  );
  await crawler.onIdle(); // Resolved when no queue is left
  await crawler.close(); // Close the crawler
};
```

**Comment by matheuschimelli** [comment]
@igna92ts why are you using map on crawler queue? I think you should don't use map iside crawler queue. I can't test it right now, but I will do.

**Comment by igna92ts** [comment]
Well, in the documentation it says I can queue multiple urls at once, I dont see the issue with that map.
Its the same as instead of doing
```
await crawler.queue(
    urlList.map(c => ({
      url: c,
      userAgent: pickRandomElement(userAgents),
      screenshot: {
        path: `./sreenshots/${Buffer.from(c).toString('base64')}.png`
      }
    }))
  );
```
doing
```
await crawler.queue(
    urlList.map([{
      url: c,
      userAgent: pickRandomElement(userAgents),
      screenshot: {
        path: `./sreenshots/${Buffer.from(c).toString('base64')}.png`
      }
    }]))
  );
```
Which, at least according to the docs, should be fine to do

**Comment by matheuschimelli** [comment]
Your code looks fine. But when you use map inside queue you are calling crawler queue only one time. I think that this could be the issue.

**Comment by igna92ts** [comment]
yes but in the documentation in the first example its also doing just that
`const HCCrawler = require('headless-chrome-crawler');

(async () => {
  const crawler = await HCCrawler.launch({
    // Function to be evaluated in browsers
    evaluatePage: (() => ({
      title: $('title').text(),
    })),
    // Function to be called with evaluated results from browsers
    onSuccess: (result => {
      console.log(result);
    }),
  });
  // Queue a request
  await crawler.queue('https://example.com/');
  // Queue multiple requests
  await crawler.queue(['https://example.net/', 'https://example.org/']);
  // Queue a request with custom options
  await crawler.queue({
    url: 'https://example.com/',
    // Emulate a tablet device
    device: 'Nexus 7',
    // Enable screenshot by passing options
    screenshot: {
      path: './tmp/example-com.png'
    },
  });
  await crawler.onIdle(); // Resolved when no queue is left
  await crawler.close(); // Close the crawler
})();`

**Comment by matheuschimelli** [comment]
Yep, you're right, but i cannot see custom options inside the crawler queue array. I've tried to use the example as you are using, but it didn't worked for me. So i had to call crawler.queue ever time i need to use it

**Comment by igna92ts** [comment]
I just tried to save a screenshot with a single queue and still didnt work 😢

**Comment by matheuschimelli** [comment]
What code are you using? Please, post your node version and environment

**Comment by igna92ts** [comment]
Im on node v8.9.4 and in maxOS high sierra v10.13.6

**Comment by matheuschimelli** [comment]
> I just tried to save a screenshot with a single queue and still didnt work 😢
> If I check whats on `result` in the `onSuccess` it does have a property screenshot but its undefined rather than being the image buffer as it said in the docs.
> Maybe im doing something else wrong? 🤔

When i use the example code provided on README, it returns the screeshot buffer. 
```javascript
result: { title: 'Example Domain' },
  screenshot:
   <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 03 20 00 00 02 58 08 06 00 00 00 9a 76 82 70 00 00 20 00 49 44 41 54 78 9c ec dd 77 54 14 d7 df ... >,
  cookies: [],
  links: [ 'http://www.iana.org/domains/example' ] }
```
I was reading the Puppeteer docs, and it says:
[Puppeteer docs](https://github.com/GoogleChrome/puppeteer/blob/v1.13.0/docs/api.md#pagescreenshotoptions)

> NOTE Screenshots take at least 1/6 second on OS X. See https://crbug.com/741689 for discussion.


But you are using MacOS Hight Sierra. I think that the bug is still alive. I tryed the demo code for a single screenshot using linux (since i don't have a mac) and  your node version and i tryed too using node 10.15.0 . For all my tests, i get the screeshot buffer. So, since i dont have a mac, i cant help you. I suggest you to try to use a newerly node.js version, and try again. If you want to use, i'll put my test code below if you want to test

```javascript
const HCCrawler = require('headless-chrome-crawler');
//const path = require("path");
const PATH = './print/';

(async() => {
  const crawler = await HCCrawler.launch({
    // Function to be evaluated in browsers
    evaluatePage: (() => ({
      title: $('title').text(),
    })),
    // Function to be called with evaluated results from browsers
    onSuccess: (result => {
      console.log(result);
    }),
  });
  await crawler.queue({
    url: 'https://example.net/',
    screenshot: {
      path: Buffer.from(`./print/PRINT.png`),
      type: 'png'
    },
  });

  await crawler.onIdle(); // Resolved when no queue is left
  await crawler.close(); // Close the crawler
})();
```

**Comment by kulikalov** [comment]
@igna92ts is this issue resolved? If so, could you post the solution summary here?

**Comment by rom3r4** [comment]
Leaving this here for posterity, since I ran into the same issue. I ran across this [link here](https://gist.github.com/valarpirai/90a67afc5cdd328055dea81cfebc5ad7), It seems to be working fine for me.


```typescript
        ...
        const crawler = await HCCrawler.launch({
            maxConcurrency: 1,
            preRequest: ((options:any) => {
                // if (!options.saveAs) return false; // Skip the request by returning false
                console.log(options)
                let splitted_url = options.url.split('/');
                let page = splitted_url[splitted_url.length - 1];
                if(!page) {
                    page = 'HOME-' + Math.floor(Math.random());
                }
                options.screenshot = {
                    path: './tmp/IMG-' + splitted_url[2] + '-' + page + '-'  + '.png',
                    fullPage: true
                };
                return true;
            }),
            evaluatePage: ...
            
         ...
         });   
```
