### ISSUE TITLE
Is it possible to use puppeteer-core to decrease install size?

### ISSUE THREAD

**Issue by riccardogiorato** [yujiosaka/headless-chrome-crawler#345]
**Problem**
The crawler currently install more than 300mb: https://packagephobia.now.sh/result?p=headless-chrome-crawler

**Solution**
We could use puppeteer-core( https://www.npmjs.com/package/puppeteer-core ) to reduce the install size with the addition of a prebuilt binary like this one: https://github.com/alixaxel/chrome-aws-lambda.

**Benefit**
Current install Size: 300mb
Future install Size: 40mb

**Examples of a similar idea?**
I had this idea after looking at this great article on how to build a server-less app with chromium: https://zeit.co/blog/serverless-chrome

**Comment by LeMoussel** [comment]
You can install `headless-chrome-crawler` without Chromium browser.
To don't download bundled Chromium during installation step, you must set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD ` environment variable. See:  https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables

For example under windows with PowerShell I do :
```
$env:PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
npm i headless-chrome-crawler --save
```

**Comment by Giorat** [comment]
After this command how can I make "headless-chrome-crawler" use a custom chrome version from "chrome-aws-lambda" @LeMoussel do you know?

**Comment by LeMoussel** [comment]
Set [puppeteer.executablePath()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerexecutablepath) option.

**Comment by kulikalov** [comment]
@riccardogiorato can we consider this issue resolved?
