### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by laoshaw** [yujiosaka/headless-chrome-crawler#359]
Last release was made 1.5 years ago, I like this over Puppeteer, however is this project still active or should I use puppeteer directly?

**Comment by matheuschimelli** [comment]
The project is not being maintained actively. But you can use it. However if you need more control over your crawler, i suggest you to use puppeteer instead of headless-chrome-crawler

**Comment by kulikalov** [comment]
hopefully, it is now... gentle reviving in progress...
