### ISSUE TITLE
Fail to insert jQuery silently due to content security policy

### ISSUE THREAD

**Issue by yujiosaka** [yujiosaka/headless-chrome-crawler#59]
It happens when you crawl GitHub pages.
See https://github.com/GoogleChrome/puppeteer/issues/1229

**Comment by chiptus** [comment]
maybe instead of adding a script tag like here: https://github.com/yujiosaka/headless-chrome-crawler/blob/master/lib/crawler.js#L195 we should add the script inline?

**Comment by yujiosaka** [comment]
@chiptus 
That should work. I found [a library](https://github.com/mhingston/dvla-scraper/blob/a180f1353bad2b5ca36ab1892759557b3493f0e1/scraper.js#L30) doing that workaround.
At the same time, using eval makes it hard to debug and CSP breaks `waitFor` function any way. See https://github.com/GoogleChrome/puppeteer/issues/1814#issuecomment-358225991 .

Let me know if you are having troubles with this issue. I'll consider doing the workaround if there are enough needs.
